name: Get Brunch Release Name
on:
  workflow_dispatch:
    inputs:
      bin_url:
        description: 'ChromeOS恢复映像地址'
        required: true
      brunch_url:
        description: 'Brunch文件链接'
jobs:
  get_release_name:
    runs-on: ubuntu-latest
    steps:
      - name: install enverment
        run: |
          sudo apt update && sudo apt -y install pv cgpt tar unzip
      - name: download Chrome OS
        run: |
          curl -o cros.zip ${{ github.event.inputs.bin_url }}
      - name: unzip
        run: |
          unzip cros.zip -d cros
      - name: Find and Rename .bin File
        run: |
          # 定义目标文件夹路径
          target_folder="cros"  # 替换为你的目标文件夹路径

          # 找到第一个 .bin 文件
          first_bin_file=$(find "$target_folder" -type f -name "*.bin" | head -n 1)

          # 检查是否找到文件
          if [ -z "$first_bin_file" ]; then
            echo "No .bin file found in $target_folder"
            exit 1  # 如果没有找到文件，退出工作流
          else
            echo "Found .bin file: $first_bin_file"
            # 重命名为 cros.bin
            mv "$first_bin_file" "$target_folder/cros.bin"
          fi
      
      - name: Download and untar
        run: |
          wget -O brch.tar.gz ${{ github.event.inputs.brunch_url }}
          tar -xvzf brch.tar.gz -C cros
      - name: build
        run: |
          cd cros
          sudo bash ./chromeos-install.sh -src cros.bin -dst chromeos.img
      - name: Upload Artifact
        uses: actions/upload-artifact@v4  # 使用 upload-artifact Action
        with:
          name: chromeos  # 工件名称
          path: cros/chromeos.img  # 要上传的文件路径
          
