name: Get Brunch Release Name
on:
  workflow_dispatch:
jobs:
  get_release_name:
    runs-on: ubuntu-latest
    steps:
      - name: Get Releases
        id: get_releases
        run: |
          releases=$(curl -s https://api.github.com/repos/sebanc/brunch/releases)
          echo "releases<<EOF" >> $GITHUB_ENV
          echo "$releases" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Filter Release Name
        id: filter_release_name
        run: |
          temp_file=$(mktemp)
          echo "$releases" > $temp_file
          release_name=$(jq -r '.[] | select(.tag_name | startswith("r131-stable-")) | .tag_name' $temp_file | head -n 1)
          rm $temp_file
          echo "release_name<<EOF" >> $GITHUB_ENV
          echo "$release_name" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - name: Print Release Name
        run: |
          echo "The first release name starting with 'r131-stable-' is: $release_name"
