name: Get Brunch Release Name

on:
  workflow_dispatch:

jobs:
  get_release_name:
    runs-on: ubuntu-latest
    steps:
      - name: Get Releases
        id: get_releases
        run: |
          releases=$(curl -s https://api.github.com/repos/sebanc/brunch/releases)
          echo "::set-output name=releases::$releases"
      - name: Filter Release Name
        id: filter_release_name
        run: |
          releases=$(echo ${{ steps.get_releases.outputs.releases }})
          release_name=$(echo $releases | jq -r '.[] | select(.tag_name | startswith("r131-stable-")) | .tag_name' | head -n 1)
          echo "::set-output name=release_name::$release_name"
      - name: Print Release Name
        run: |
          echo "The first release name starting with 'r131-stable-' is: ${{ steps.filter_release_name.outputs.release_name }}"
